document.getElementById("message").innerHTML="<p style='cursor:pointer;padding:10px;background-color:gold;color:black; outline:3px solid red;'id='message' onclick='op()'>OPEN NOTIFICATION &#8659 </p>";
function op(){
document.getElementById("noti").innerHTML="<p style='cursor:pointer;padding:10px; background-color:red;color:black; outline:3px solid white;cursor:pointer;' id='message' onclick='cl()'>CLOSE NOTIFICATION &#8657</p><p style='background-image: linear-gradient(to right, #43e97b 0%, #38f9d7 100%); color:black;'>:-) <p  style='background-image: linear-gradient(to right, #43e97b 0%, #38f9d7 100%); color:black;'id='dt'></p><br><b style='background-image: linear-gradient(to right, #43e97b 0%, #38f9d7 100%); color:black;'><u>NOTIFICATION:</u></b><br><b style='background-image: linear-gradient(to right, #43e97b 0%, #38f9d7 100%); color:black;'id='dt'></p><br><b style='background-image: linear-gradient(to right, #43e97b 0%, #38f9d7 100%); color:black;'>***SOME CONTENT MAY NOT SUPPORT ON PC.<BR>BUT ALL THE CONTENT CAN STREAMED ON MOBILE.***</b><br> <embed src='https://spark00001.github.io/images/qr.png' style='width:100px;height:100px;' download></embed><br><p style='color:black;'>DONATE US( MIN. Rs. 1)</p><br><table><tr><td><button style='background-color:gold;color:black;outline:5px solid black;'>ABOUT SITE</button></td><td><button style='cursor:pointer;background-color:gold;color:black;outline:5px solid black;'>ABOUT DEVELOPER</td><td><button onclick='chatimg()' style='cursor:pointer;background-color:gold;color:black;outline:5px solid black;'>HOW TO CHAT</td></tr></table></br></p>";
document.getElementById("message").style.display="none";
const dt = new Date();
document.getElementById("dt").innerHTML=dt;
document.getElementById("noti").style.backgroundImage="linear-gradient(to right, #43e97b 0%, #38f9d7 100%)";
}
function cl(){
document.getElementById("noti").innerHTML="<p style=' cursor:pointer;padding:10px;background-color:gold;color:black; outline:3px solid red;' id='message' onclick='op()'>OPEN NOTIFICATION &#8659</p>";
}
function chatimg(){
document.getElementById("noti").innerHTML="<p style='cursor:pointer;padding:10px; background-color:red;color:black; outline:3px solid white;cursor:pointer;' id='message' onclick='cl()'>CLOSE NOTIFICATION &#8657</p><br><button onclick='op()' style='cursor:pointer;background-color:gold;color:black;outline:5px solid black;'>&#8656; PREVIOUS PAGE</button><br><embed src='https://spark00001.github.io/images/chat.png' style='width:99%;height:400px;'></embed><br><table><tr><td><button style='background-color:gold;color:black;outline:5px solid black;'>ABOUT SITE</button></td><td><button style='cursor:pointer;background-color:gold;color:black;outline:5px solid black;'>ABOUT DEVELOPER</td><td><button onclick='chatimg()' style='cursor:pointer;background-color:gold;color:black;outline:5px solid black;'>HOW TO CHAT</button></td></tr></table>";
}
